//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using MBran.SitemapXml.Models;
using MBran.SitemapXml.ValueConverter;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1115 with alias "hasSiteMap"
	/// <summary>_HasSiteMap</summary>
	public partial interface IHasSiteMap : IPublishedContent
	{
		/// <summary>sitemapOption</summary>
		SitemapOptions SitemapOption { get; }
	}

	/// <summary>_HasSiteMap</summary>
	[PublishedContentModel("hasSiteMap")]
	public partial class HasSiteMap : PublishedContentModel, IHasSiteMap
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasSiteMap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasSiteMap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasSiteMap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// sitemapOption
		///</summary>
		[ImplementPropertyType("sitemapOption")]
		public SitemapOptions SitemapOption
		{
			get { return GetSitemapOption(this); }
		}

		/// <summary>Static getter for sitemapOption</summary>
		public static SitemapOptions GetSitemapOption(IHasSiteMap that) { return that.GetPropertyValue<SitemapOptions>("sitemapOption"); }
	}
}
